# Generated by Django 5.0.1 on 2024-01-19 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default=datetime.datetime(2024, 1, 19, 1, 48, 49, 790021, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
