# Generated by Django 5.0.1 on 2024-01-29 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='subjet',
            new_name='subject',
        ),
    ]
