# Generated by Django 5.0.1 on 2024-01-24 15:49

import django.db.models.deletion
import ecommerce.models
import shortuuid.django_fields
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='cat', unique=True)),
                ('title', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='category.jpg', upload_to='category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Product Reviews',
            },
        ),
        migrations.CreateModel(
            name='CartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default='0.99', max_digits=99999999999999)),
                ('paid_status', models.BooleanField(default=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('product_status', models.CharField(choices=[('published', 'Published'), ('process', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('published', 'Published')], default='processing', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cart Order',
            },
        ),
        migrations.CreateModel(
            name='CartOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=200)),
                ('product_status', models.CharField(max_length=200)),
                ('item', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('qty', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default='0.99', max_digits=99999999999999)),
                ('total', models.DecimalField(decimal_places=2, default='0.99', max_digits=99999999999999)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.cartorder')),
            ],
            options={
                'verbose_name_plural': 'Cart Order Items',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='pro', unique=True)),
                ('title', models.CharField(default='Product', max_length=100)),
                ('image', models.ImageField(default='product.jpg', upload_to=ecommerce.models.user_directory_path)),
                ('small_description', models.TextField(blank=True, default='This is a small product', null=True)),
                ('description', models.TextField(blank=True, default='This is the product', null=True)),
                ('price', models.DecimalField(decimal_places=2, default='0.99', max_digits=99999999999999)),
                ('old_price', models.DecimalField(decimal_places=2, default='2.99', max_digits=99999999999999)),
                ('specifications', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, default='Organic', max_length=100, null=True)),
                ('stock_count', models.CharField(blank=True, default='12', max_length=100, null=True)),
                ('waranty', models.CharField(blank=True, default='1', max_length=100, null=True)),
                ('mfd', models.DateTimeField(blank=True, null=True)),
                ('p_quantity', models.CharField(default='2 shoes', max_length=100)),
                ('frame', models.CharField(default='Iron', max_length=10)),
                ('weight_wo_wheels', models.CharField(default='20LBS', max_length=10)),
                ('weight_capacity', models.CharField(default='80LBS', max_length=10)),
                ('size', models.CharField(default='All Sizes', max_length=10)),
                ('product_status', models.CharField(choices=[('published', 'Published'), ('process', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('published', 'Published')], default='in_review', max_length=10)),
                ('p_return', models.CharField(choices=[('No Return Policy', 'No Return Policy'), ('7 Days Return Policy', '7 Days Return Policy')], default='7 Days Return Policy', max_length=50)),
                ('cod', models.CharField(choices=[('Cash on Delivery Available', 'Cash on Delivery Available'), ('Cash on Delivery is not Available', 'Cash on Delivery is not Available')], default='Cash on Delivery Available', max_length=50)),
                ('color', models.CharField(blank=True, choices=[('black', 'Black'), ('blue', 'Blue'), ('red', 'Red'), ('white', 'White'), ('purple', 'Purple'), ('green', 'Green'), ('orange', 'Orange'), ('cyan', 'Cyan')], max_length=50, null=True)),
                ('Type_of_packing', models.CharField(blank=True, choices=[('Rigid Boxes', 'Rigid Boxes'), ('Paperboard', 'Paperboard'), ('Chipboard', 'Chipboard'), ('Corrugated Cardboard', 'Corrugated Cardboard'), ('Cotton', 'Cotton'), ('Plastics', 'Plastics'), ('Foil Sealed Bags', 'Foil Sealed Bags'), ('Jute (Hessian/Burlap)', 'Jute (Hessian/Burlap)'), ('Envelopes / Bubble Mailers', 'Envelopes / Bubble Mailers')], default='Foil Sealed Bags', max_length=50, null=True)),
                ('status', models.BooleanField(default=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('digital', models.BooleanField(default=False)),
                ('sku', shortuuid.django_fields.ShortUUIDField(alphabet='ABCD1234', length=10, max_length=20, prefix='SKU', unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='ecommerce.category')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='product.jpg', upload_to='product-images')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_images', to='ecommerce.product')),
            ],
            options={
                'verbose_name_plural': 'Products Images',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '⭐✰✰✰✰'), (2, '⭐⭐✰✰✰'), (3, '⭐⭐⭐✰✰'), (4, '⭐⭐⭐⭐✰'), (5, '⭐⭐⭐⭐⭐')], default=None)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Product Reviews',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='ven', unique=True)),
                ('title', models.CharField(default='Vendor', max_length=100)),
                ('image', models.ImageField(default='vendor.jpg', upload_to=ecommerce.models.user_directory_path)),
                ('cover_image', models.ImageField(default='vendor.jpg', upload_to=ecommerce.models.user_directory_path)),
                ('description', models.TextField(blank=True, default='I am an Amazing Vendor', null=True)),
                ('address', models.CharField(default='123 casabarata', max_length=100)),
                ('contact', models.CharField(default='+212 65447xx120', max_length=100)),
                ('chat_resp_time', models.CharField(default='100', max_length=100)),
                ('shipping_on_time', models.CharField(max_length=100)),
                ('authentic_rating', models.CharField(max_length=100)),
                ('days_return', models.CharField(max_length=100)),
                ('warranty_period', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vendors',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='ecommerce.vendor'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Wishlists',
            },
        ),
    ]
