# Generated by Django 5.0.1 on 2024-01-25 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_vendor_facebook_vendor_instagram_vendor_linkedin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={},
        ),
    ]
