# Generated by Django 5.0.1 on 2024-01-23 11:07

import ecommerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_product_vendor_vendor_date_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='cover_image',
            field=models.ImageField(default='vendor.jpg', upload_to=ecommerce.models.user_directory_path),
        ),
    ]
