# Generated by Django 5.0.1 on 2024-01-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_product_mfd_product_stock_count_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cod',
            field=models.CharField(blank=True, default='Available', max_length=100, null=True),
        ),
    ]
