# Generated by Django 5.0.1 on 2024-01-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_product_cod'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='producr_return',
            field=models.CharField(blank=True, choices=[('No Return Policy', 'No Return Policy'), ('7 Days Return Policy', '7 Days Return Policy')], default='7 Days Return Policy', max_length=50, null=True),
        ),
    ]
