# Generated by Django 5.0.1 on 2024-01-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_product_producr_return'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='producr_return',
        ),
        migrations.AddField(
            model_name='product',
            name='p_return',
            field=models.CharField(choices=[('No Return Policy', 'No Return Policy'), ('7 Days Return Policy', '7 Days Return Policy')], default='7 Days Return Policy', max_length=50),
        ),
    ]
