# Generated by Django 5.0.1 on 2024-01-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_remove_product_producr_return_product_p_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cod',
            field=models.CharField(choices=[('Cash on Delivery Available', 'Cash on Delivery Available'), ('Cash on Delivery is not Available', 'Cash on Delivery is not Available')], default='Cash on Delivery Available', max_length=50),
        ),
    ]
