# Generated by Django 5.0.1 on 2024-01-23 20:15

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_alter_product_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='ABCD1234', length=10, max_length=20, prefix='SKU', unique=True),
        ),
    ]
