# Generated by Django 5.0.1 on 2024-01-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('blue', 'Blue'), ('red', 'Red'), ('white', 'White')], max_length=50, null=True),
        ),
    ]
