# Generated by Django 5.0.1 on 2024-01-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('blue', 'Blue'), ('red', 'Red'), ('white', 'White'), ('purple', 'Purple'), ('green', 'Green'), ('orange', 'Orange'), ('cyan', 'Cyan')], max_length=50, null=True),
        ),
    ]
