# Generated by Django 5.0.1 on 2024-01-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_alter_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='small_description',
            field=models.TextField(blank=True, default='This is a small product', null=True),
        ),
    ]
