# Generated by Django 5.0.1 on 2024-01-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_product_small_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Red', 'Red'), ('White', 'White'), ('Purple', 'Purple'), ('Green', 'Green'), ('Orange', 'Orange'), ('Cyan', 'Cyan')], max_length=50, null=True),
        ),
    ]
