# Generated by Django 5.0.1 on 2024-01-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_product_type_of_packing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Type_of_packing',
            field=models.CharField(blank=True, choices=[('Rigid Boxes', 'Rigid Boxes'), ('Paperboard', 'Paperboard'), ('Chipboard', 'Chipboard'), ('Corrugated Cardboard', 'Corrugated Cardboard'), ('Cotton', 'Cotton'), ('Plastics', 'Plastics'), ('Foil Sealed Bags', 'Foil Sealed Bags'), ('Jute (Hessian/Burlap)', 'Jute (Hessian/Burlap)'), ('Envelopes / Bubble Mailers', 'Envelopes / Bubble Mailers')], default='Foil Sealed Bags', max_length=50, null=True),
        ),
    ]
