# Generated by Django 5.0.1 on 2024-01-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_alter_product_type_of_packing'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_quantity',
            field=models.CharField(default='2 shoes', max_length=100),
        ),
    ]
