# Generated by Django 5.0.1 on 2024-01-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_product_p_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='frame',
            field=models.CharField(default='Iron', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='M, S', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_capacity',
            field=models.CharField(default='80LBS', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_wo_wheels',
            field=models.CharField(default='20LBS', max_length=10),
        ),
    ]
