# Generated by Django 5.0.1 on 2024-01-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0024_product_frame_product_size_product_weight_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(default='All Size', max_length=10),
        ),
    ]
