# Generated by Django 5.0.1 on 2024-01-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0025_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(default='All Sizes', max_length=10),
        ),
    ]
